### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by kmsalah** [CarolinaIgnites/editFrame#12]
Utilize igniteApi to upload images

**Comment by dmadisetti** [comment]
Todos:
 - Add image tab
   - Allow upload
   - Allow link
   - Stuff into cache
   - Allow label for image reference in HTML.
     - e.g. `https://myrealllyylonglink.com/meme.png -> gf://meme.png`
     - now in HTML `<circle src="gf://meme.png">`

On api side, implement LRU in reddis to prevent abuse. This can still be relatively large 

Please leverage

https://github.com/CarolinaIgnites/editFrame/tree/external_cache

And

https://github.com/CarolinaIgnites/gameFrame/tree/external_cache
