### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by dmadisetti** [CarolinaIgnites/editFrame#8]
Just putting it out there

**Comment by pbateman828** [comment]
Are we looking to do our own implementation or import it? 

Here's a nifty one 
https://github.com/google/code-prettify

Instead of downloading and adding files, we would just throw in a URL with whichever highlight scheme we like

**Comment by dmadisetti** [comment]
That would be ideal. Show me if you can get it to work. From the looks of prettyprint, it's not ideal for dynamic text editing. 

Atom is written on top of electron, so maybe GitHub has some inbrowser tools.

**Comment by dmadisetti** [comment]
Closed by #10
